apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - image: albertogarces/nodeapp-01:v01
          name: nodeapp
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /liveOK
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyOK
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: config-volume
              mountPath: /data-env-configmap
            - name: secret-volume
              mountPath: /data-env-secret
            - name: common-volume
              mountPath: /data-common-configmap
          env:
            - name: VAR_1
              valueFrom:
                configMapKeyRef:
                  name: example-configmap-1
                  key: env_var_1
            - name: VAR_SECRET_USERNAME_1
              valueFrom:
                secretKeyRef:
                  name: example-secret-1
                  key: username1
      volumes:
        - name: config-volume
          configMap:
            name: example-configmap-1
        - name: secret-volume
          secret:
            secretName: example-secret-1
        - name: common-volume
          configMap:
            name: common-configmap-1
            
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: nodeapp
