apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

namespace: test-kustomize-pre

# commonLabels:
#   version: "01"

# commonAnnotations:
#   anotacion: aaa

# namePrefix: pre-

# nameSuffix: "-001"

configMapGenerator:
  - name: example-configmap-1
    files:
      - application.properties
    envs:
      - pre.properties
    literals:
      - env_var_3=ccc_pre

secretGenerator:
  - name: example-secret-1
    files:
      - application.secret.properties
    envs:
      - pre.secret.properties
    literals:
      - username2=admin_pre2
      - password2=secretPass_pre_2

generatorOptions:
  disableNameSuffixHash: true
  # this labels and annotations will be added to the configMaps/secrets generated
  labels:
    mylabel: label-value
  annotations:
    myannotation: annotation-value
